/*
 * store — per-user record of saved shares, and their passwords in KWallet.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 *
 * All of this is unprivileged and lives in the user's own session. The helper
 * never reads it: the dialog and KCM look the password up here and pass it
 * over the KAuth call, so no password is ever written to a persistent file on
 * disk.
 *
 * Records and wallet entries are keyed by a stable per-share id (plan §5.1),
 * not by mount point or "username@unc" — the latter is shared by two
 * configured shares of the same share and user, so deleting either would
 * revoke both. The id is root-generated by the helper and returned from
 * `define`/`definesystem` (plan §1.6.2); Store never invents one of its own,
 * so a definition and its config record can never disagree about identity.
 *
 * `mode` and `rememberPassword` here are user-writable convenience data, not
 * authoritative: the root-owned unit marker decides mode and authentication
 * (plan §6.1, §13). A caller that finds Store disagreeing with the marker
 * must trust the marker and report the row as Drift — Store is not consulted
 * for that decision.
 */

#pragma once

#include "unitvalue.h"

#include <QList>
#include <QString>

namespace Store
{

/** One saved share, as recorded in ~/.config/nasmountrc. */
struct Share {
    QString id; ///< root-generated by the helper; stable for the life of the share
    QString unc;
    QString mountPoint;
    QString username;
    QString domain;
    bool reconnect = false; ///< armed automatically by the session supervisor at sign-in; Session mode only
    UnitValue::CredentialMode mode = UnitValue::CredentialMode::Session; ///< convenience only -- see file header
    bool rememberPassword = false; ///< true only once the wallet write it describes is confirmed (plan §13.3)
};

/**
 * A share as read from config, together with the generation it was read at —
 * the token a later checked commit must present unchanged for the write to
 * succeed (plan §1.6.3). `exists` is false for an id with no record at all.
 * `corrupt` is true for a group that is present but missing a required field
 * (empty Unc or MountPoint) — surfaced, never silently skipped (plan
 * §1.6.5); `share` on a corrupt snapshot carries whatever fields were
 * readable, for display, but must not be trusted as a complete record.
 */
struct Snapshot {
    Share share;
    quint64 generation = 0;
    bool exists = false;
    bool corrupt = false;
};

/**
 * Every share group in config, in the order KConfig lists them, each as a
 * full Snapshot — including corrupt groups (plan §1.6.5). Callers that only
 * want well-formed, existing shares should filter on `!corrupt`, or use
 * shares() below.
 */
QList<Snapshot> shareSnapshots();

/** Convenience over shareSnapshots(): only the well-formed shares, in the
 *  same order. What every caller before plan §1.6 used. */
QList<Share> shares();

/** Reads one share's current snapshot; `exists` is false if the id has no record. */
Snapshot snapshotById(const QString &id);

enum class CommitResult {
    Ok,
    GenerationConflict, ///< the record changed since it was read; the caller's snapshot is stale
    SyncFailed,         ///< KConfig::sync() itself failed -- a real failure, never silently ignored
};

/**
 * Checked compare-and-swap write of one share record (plan §1.6.3).
 *
 * To insert a brand-new record, pass `expectedGeneration == 0`; this fails
 * with GenerationConflict if a record with `share.id` already exists. To
 * update an existing record, pass exactly the generation a prior
 * snapshotById()/shareSnapshots() call returned for it; this fails with
 * GenerationConflict if that is no longer current (deleted, or written by
 * someone else since). The per-user lock (Session::UserLock) must be held
 * by the caller across the read that produced `expectedGeneration` and this
 * commit — the generation check catches a bug that drops the lock, it does
 * not replace holding it (plan §1.6.4).
 */
CommitResult commitShare(const Share &share, quint64 expectedGeneration, QString *error);

/** Removes a share record and, if present, its stored password. Deletes the
 *  wallet entry first and only removes the config group once that is
 *  confirmed, so a crash between the two never leaves an unindexed wallet
 *  secret (plan §13.3). Returns false — record left in place — if wallet
 *  cleanup could not be confirmed. */
bool removeShare(const QString &id);

/**
 * Reads a share's password from KWallet.
 *
 * Returns false when there is no stored password, or when the wallet is
 * unavailable or the user declined to unlock it — the caller should then ask.
 *
 * With `onlyIfUnlocked`, returns false immediately rather than opening a locked
 * wallet. The sign-in supervisor uses that: openWallet() is synchronous and
 * will put an unlock prompt on screen, which is exactly what unattended arming
 * at sign-in must not do (plan §7.1).
 */
bool readPassword(const QString &id, QString *password, bool onlyIfUnlocked = false);

/** True when the network wallet is already open, i.e. readable without prompting. */
bool walletIsOpen();

/**
 * Stores a password in KWallet, replacing any previous one.
 *
 * Returns false if the wallet could not be opened, in which case the mount can
 * still proceed for this session; only the "remember" part is lost. A caller
 * must not set Share::rememberPassword true, via commitShare(), unless this
 * returned true first (plan §1.6.6).
 */
bool writePassword(const QString &id, const QString &password);

/** Returns false if the wallet could not be opened or the removal could not
 *  be confirmed; the caller must not report the password removed. */
bool removePassword(const QString &id);

/** Removes the complete application KWallet folder, then the configuration
 * file. Both operations are checked; wallet unavailability is a failure. */
bool purgeApplicationData(QString *error);

} // namespace Store
